services:
  # POSTGRESQL DATABASE SERVICE
  postgres:
    image: postgres
    container_name: microservices-playground-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: payment-db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /docker-entrypoint-initdb.d 
    networks:
      - microservices-playground-network
    restart: unless-stopped

  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: microservices-playground-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"
    networks:
      - microservices-playground-network
    restart: unless-stopped
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: microservices-playground-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
    networks:
      - microservices-playground-network
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    

networks:
  microservices-playground-network:
    driver: bridge
volumes:
  postgres_data:
