spring.application.name=payment-web
server.port=8765

logging.level.com.playground=DEBUG
logging.level.org.springframework.web=INFO

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always