spring:
    application:
        name: inventory-service
    config:
        #indique la source confi qui tourne sur http://localhost:8888
        import: "optional:configserver:http://localhost:8888"


