server:
  port: 8080

spring:
    cloud:
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: true
                            lowerCaseServiceId: true
